# Generated by Django 6.0.5 on 2026-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_rename_book_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
