# Generated by Django 6.0.5 on 2026-05-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='description',
            new_name='designation',
        ),
    ]
